# Generated by Django 3.0.7 on 2020-06-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='filename')),
            ],
        ),
    ]
