# Generated by Django 3.0.7 on 2020-06-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='pdf',
            field=models.FileField(upload_to='directory/file'),
        ),
    ]
