# Generated by Django 3.0.7 on 2020-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20200624_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
